### ISSUE TITLE
Closing (working in background scheduler) if any

### ISSUE THREAD

**Issue by omer73364** [verful/adonis-scheduler#88]
How to close the scheduler from background, or restart it if possible?

**Comment by arthur-er** [comment]
The scheduler always is in foreground when you run the `node ace scheduler:work` command, to restart simply stop and start again

**Comment by omer73364** [comment]
No, I run it in the ssh terminal of my server in the background.. Then when I connect to ssh again.. I can't stop it easily
I keep the pid of scheduler process so I can stop it only by killing it using its pid

**Comment by arthur-er** [comment]
Run it as a systemd service, if you don't have access to systemd or any service manager, use pm2

**Comment by omer73364** [comment]
> Run it as a systemd service

OK, I will try this.. Thank you

**Comment by alessandrodias** [comment]
Can you please provide an example of how can I run this alongside with my server, using PM2?

**Comment by arthur-er** [comment]
> Can you please provide an example of how can I run this alongside with my server, using PM2?

https://chatgpt.com/share/2611cb97-aab2-4780-93f5-105f82c8311c
